---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: yes

- name: Install Dependencies
  ansible.builtin.apt:
    name:
     - software-properties-common
     - apache2
     - zip
     - unzip
    state: latest
    update_cache: yes

- name: 
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  ansible.builtin.apt:
    name:
     - php7.2
     - libapache2-mod-php7.2
     - php7.2-common
     - php7.2-curl
     - php7.2-intl
     - php7.2-mbstring
     - php7.2-xmlrpc
     - php7.2-mysql
     - php7.2-gd
     - php7.2-pgsql
     - php7.2-xml
     - php7.2-cli
     - php7.2-imagick
     - php7.2-bcmath
     - php7.2-gmp
     - php7.2-zip
    state: latest
    update_cache: yes